/**
 * Auto-generate conversation titles via Haiku.
 *
 * Collects user messages AND assistant text blocks from the conversation
 * and sends them to the daemon's llm_complete endpoint so the title
 * reflects the full scope of the conversation.
 *
 * Title generation is deferred until the first AI response completes
 * (via `streaming_stopped`) so there's enough context to produce a
 * meaningful name. Re-generation can be triggered manually with
 * `/rename` (no args), or automatically when the conversation has
 * grown significantly since the last auto-title.
 */

import type { DaemonClient } from "./client";
import type { RenderState } from "./state";
import { getMarkPrefix } from "./marks";

// ── Prompt ─────────────────────────────────────────────────────────

const INSTRUCTION = `You generate short conversation titles. Output ONLY the title — 2 to 5 lowercase words, no quotes, no punctuation, no explanation. Be specific: prefer concrete nouns, tool/feature names, and actions over vague descriptions. Match this naming style:
exo bash truncate, exo code qa, berlin airbnb, tokens bug, context tool, unbricking convo, merging img pasting, netherlands trains, exo vim linewrapping, exo msg queuing, fixing message queuing, airpods pro autoconnect, discord streaming, context management, sauron digest parsing, sidebar scroll fix, haiku title regen`;

// Must exceed the thinking budget (10000) configured in api.ts for
// non-adaptive models — otherwise all tokens go to thinking and the
// text response is empty.
const MAX_TOKENS = 10200;

/** Max characters of conversation context to send for title generation. */
const MAX_CONTEXT_CHARS = 4000;

/** Placeholder title shown while generation is in-flight. */
export const PENDING_TITLE = "pending";

/**
 * Number of completed AI responses before auto-regenerating the title.
 * The first generation happens after response 1. Subsequent auto-regens
 * happen at this interval (e.g. every 5 responses) to capture topic drift.
 */
const REGEN_INTERVAL = 5;

// ── Tracking ──────────────────────────────────────────────────────

/**
 * Track per-conversation state for auto-titling:
 * - responseCount: how many AI responses have completed
 * - lastTitledAt: responseCount when we last generated a title
 * - autoGenerated: whether the current title was auto-generated (vs manual)
 */
interface TitleState {
  responseCount: number;
  lastTitledAt: number;
  autoGenerated: boolean;
}

const titleStates = new Map<string, TitleState>();

function getTitleState(convId: string): TitleState {
  let ts = titleStates.get(convId);
  if (!ts) {
    ts = { responseCount: 0, lastTitledAt: 0, autoGenerated: false };
    titleStates.set(convId, ts);
  }
  return ts;
}

/** Clean up tracking state when a conversation is deleted. */
export function clearTitleState(convId: string): void {
  titleStates.delete(convId);
}

// ── Helpers ────────────────────────────────────────────────────────

/**
 * Extract conversation context from both user and assistant messages.
 *
 * Strategy: take from the START of the conversation (to capture the
 * original topic) and the END (to capture where it evolved to).
 * This gives the LLM the best shot at a title that covers the full scope.
 */
function extractConversationContext(state: RenderState): string {
  // Budget: 60% from the start, 40% from the end
  const startBudget = Math.floor(MAX_CONTEXT_CHARS * 0.6);
  const endBudget = MAX_CONTEXT_CHARS - startBudget;

  // Collect text from all messages (user + assistant text blocks)
  const allTexts: { role: string; text: string }[] = [];
  for (const msg of state.messages) {
    if (msg.role === "user" && "text" in msg) {
      allTexts.push({ role: "user", text: msg.text });
    } else if (msg.role === "assistant" && "blocks" in msg) {
      // Extract only text blocks from assistant (skip thinking, tool calls)
      for (const block of msg.blocks) {
        if (block.type === "text" && block.text.trim()) {
          allTexts.push({ role: "assistant", text: block.text });
        }
      }
    }
  }

  if (allTexts.length === 0) return "";

  // Collect from start
  const startParts: string[] = [];
  let startTotal = 0;
  for (const entry of allTexts) {
    const remaining = startBudget - startTotal;
    if (remaining <= 0) break;
    const label = entry.role === "user" ? "User" : "Assistant";
    const chunk = `${label}: ${entry.text.slice(0, remaining)}`;
    startParts.push(chunk);
    startTotal += chunk.length;
  }

  // Collect from end (reversed, then un-reverse)
  const endParts: string[] = [];
  let endTotal = 0;
  for (let i = allTexts.length - 1; i >= 0; i--) {
    const remaining = endBudget - endTotal;
    if (remaining <= 0) break;
    const entry = allTexts[i];
    const label = entry.role === "user" ? "User" : "Assistant";
    const chunk = `${label}: ${entry.text.slice(0, remaining)}`;
    // Skip if already included in start section
    if (startTotal < startBudget || i >= allTexts.length - 1) {
      // Check overlap: if this entry was already fully captured by startParts
      const startEntryCount = startParts.length;
      if (i < startEntryCount) continue;
    }
    endParts.unshift(chunk);
    endTotal += chunk.length;
  }

  // Combine
  const combined = [...startParts];
  if (endParts.length > 0 && startParts.length < allTexts.length) {
    combined.push("...");
    combined.push(...endParts);
  }

  return combined.join("\n\n");
}

// ── Public API ─────────────────────────────────────────────────────

/**
 * Generate (or regenerate) a title for the given conversation.
 * Called manually via `/rename` or automatically on streaming_stopped.
 */
export function generateTitle(
  convId: string,
  state: RenderState,
  daemon: DaemonClient,
  scheduleRender: () => void,
): void {
  const context = extractConversationContext(state);
  if (!context) return; // Nothing to title

  const prompt = `${INSTRUCTION}\n\nHere is the conversation to generate a title for:\n<conversation>\n${context}\n</conversation>`;

  // Preserve any emoji mark prefix across title regeneration
  const existingTitle = state.sidebar.conversations.find(c => c.id === convId)?.title ?? "";
  const markPrefix = getMarkPrefix(existingTitle);

  const ts = getTitleState(convId);

  daemon.llmComplete(
    "",
    prompt,
    (generatedTitle) => {
      let title = generatedTitle.trim().toLowerCase().replace(/["""''`.]/g, "");
      if (markPrefix) title = markPrefix + " " + title;
      daemon.renameConversation(convId, title);
      const conv = state.sidebar.conversations.find(c => c.id === convId);
      if (conv) conv.title = title;
      ts.autoGenerated = true;
      ts.lastTitledAt = ts.responseCount;
      scheduleRender();
    },
    (error) => {
      state.messages.push({ role: "system", text: `✗ Title generation failed: ${error}`, metadata: null });
      scheduleRender();
    },
    "haiku",
    MAX_TOKENS,
  );
}

/**
 * Called when a streaming response completes for a conversation.
 * Handles initial title generation (after first response) and
 * periodic auto-regeneration for long-running conversations.
 */
export function onResponseComplete(
  convId: string,
  state: RenderState,
  daemon: DaemonClient,
  scheduleRender: () => void,
): void {
  const ts = getTitleState(convId);
  ts.responseCount++;

  const conv = state.sidebar.conversations.find(c => c.id === convId);
  const currentTitle = conv?.title ?? "";

  // Case 1: First response — always generate title
  // (title is still "pending" from conversation creation)
  if (currentTitle === PENDING_TITLE || ts.responseCount === 1) {
    generateTitle(convId, state, daemon, scheduleRender);
    return;
  }

  // Case 2: Auto-regen at intervals, but only if the title was auto-generated
  // (don't overwrite manually set titles)
  if (
    ts.autoGenerated &&
    ts.responseCount - ts.lastTitledAt >= REGEN_INTERVAL
  ) {
    generateTitle(convId, state, daemon, scheduleRender);
  }
}

/**
 * Mark a conversation's title as manually set (disables auto-regen).
 */
export function markManualTitle(convId: string): void {
  const ts = getTitleState(convId);
  ts.autoGenerated = false;
}
